import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { City, SiteData } from "./schema.js";
import { PHRASES, PACKING_LIST } from "./curated.js";

/** Order cities by the trip's intended sequence; unknown cities go last. */
const CITY_ORDER = ["rome", "naples", "positano", "sorrento", "amalfi", "pompeii"];

export async function buildSiteData(dataDir: string): Promise<SiteData> {
  let files: string[] = [];
  try {
    files = (await readdir(dataDir)).filter((f) => f.endsWith(".json"));
  } catch {
    files = [];
  }

  const cities: City[] = [];
  for (const f of files) {
    const raw = await readFile(join(dataDir, f), "utf8");
    cities.push(JSON.parse(raw) as City);
  }
  cities.sort((a, b) => {
    const ia = CITY_ORDER.indexOf(a.slug);
    const ib = CITY_ORDER.indexOf(b.slug);
    return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib);
  });

  return {
    builtLabel: "Italy · Early October 2026",
    cities,
    phrases: PHRASES,
    packingList: PACKING_LIST,
  };
}

export async function writeDataBundle(data: SiteData, siteJsDir: string): Promise<void> {
  await mkdir(siteJsDir, { recursive: true });
  const banner =
    "/* AUTO-GENERATED by `pnpm build`. Source of truth: data/*.json. Do not edit by hand. */\n";
  const body = `window.__ITALY__ = ${JSON.stringify(data, null, 2)};\n`;
  await writeFile(join(siteJsDir, "data.js"), banner + body, "utf8");
}
